version: '3.7'
services:
    service_1:
        image: vikhilp98/s1
        build: ./service-1
        ports:
            - '5000:5000'
    service_2:
        image: vikhilp98/s2
        build: ./service-2
        ports:
            - '5001:5001'
    service_3:
        image: vikhilp98/s3
        build: ./service-3
        ports:
            - '5002:5002'
    service_4:
        image: vikhilp98/s4
        build: ./service-4
        ports:
            - '5003:5003'
    