pipeline {
    agent any
    environment{
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
        install = "false"
        DATABASE_URI = credentials("DATABASE_URI")
        SECRET_KEY = credentials("SECRET_KEY")
    }
    stages {
        stage('Setup'){
            steps{
                script{
                    if (env.install == "true"){
                        sh "bash jenkins/setupscripts.sh"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/testingscripts.sh"
            }
        }

        stage('Build') {
            steps {
                sh "sudo docker-compose build --parallel"
            }
        }
        stage('Push') {
            steps {
                sh "docker-compose push"
            }
        }
        stage('Ansible') {
            steps {
                sh "cd ansible && ansible-playbook -i inventory.yaml playbook.yaml"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
        
    }
}